modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/Foxyas/Changed-Additions/issues"

[[mods]]
modId="changed_additions"
version="0.0.6"
displayName="Changed Additions"
credits="LTXProgrammer for Changed mod"
logoFile="logo.png"
updateJSONURL="https://raw.githubusercontent.com/foxyas/Changed-additions/master/update.json"
displayURL="https://github.com/Foxyas/Changed-Additions/tree/main"
authors="Foxyas"
description="Adds extra content to the Changed Mod by LtxProgrammer but keeping a Vanilla style\nPatreon: https://www.patreon.com/Changedaddonplus"

[[dependencies.changed_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.changed_additions]]
    modId="changed"
    mandatory=true
    versionRange="[0.14.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.changed_additions]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

