modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/Foxyas/Changed-Additions/issues

[[mods]]
modId="changed_additions"
version="0.0.1"
displayName="Changed Additions"
credits="LTXProgrammer for Changed mod"
logoFile="logo.png"
displayURL="https://github.com/Foxyas/Changed-Additions/tree/main"
authors="Foxyas"

[[dependencies.changed_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.changed_additions]]
    modId="changed"
    mandatory=true
    versionRange="[0.14c,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.changed_additions]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

